name: Terraform Dev Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Dev
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: environments/dev

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2️⃣ Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 3️⃣ Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 4️⃣ Terraform Init
      - name: Terraform Init
        run: terraform init -input=false

      # 5️⃣ Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # 6️⃣ Terraform Plan
      - name: Terraform Plan
        run: terraform plan -input=false

      # 7️⃣ Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
